### Creating Numpy Arrays from Python Lists

In [170]:
import numpy as np
# Use numpy array
np.array([1,2,3,4])


array([1, 2, 3, 4])

In [ ]:
# Về kiểu dữ liệu trong 1 mảng
# Nếu là python: Thì một mảng có thể có các phần tử khác kiểu dữ liệu
# Nếu là np Array: Thì nó sẽ biến các phần tử trên thành cùng 1 kiểu dữ liệu
# Ví dụ:
[3.14,4,2,3]

[3.14, 4, 2, 3]

In [ ]:
# Khi sử dụng npArray thì nó sẽ chuyển về kiểu dữ liệu cấp cao nhất (trong trường hợp này là float)
np.array([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

In [89]:
# Ngoài ra, ta có thể specify kiểu dữ liệu cho nó
np.array([1,2,3,4], dtype="float32")

array([1., 2., 3., 4.], dtype=float32)

In [90]:
# Gán mảng np cho 1 biến
a1 = np.array([1,2,3,4])
type(a1)

numpy.ndarray

In [91]:
# Mảng 2 chiều
a2 = np.array([[1,2,3],[4,5,6]])

In [92]:
# Lấy số dòng số cột
a2.shape

(2, 3)

In [93]:
# Số chiều
a2.ndim

2

In [94]:
# Xác định kiểu dữ liệu của np Arr
a2.dtype

dtype('int64')

In [95]:
# Lấy kích thước của npArr
a2.size

6

### Creating Numpy Arrays from Scratch

##### `zeros`, `ones`, `full`, `arange`, `linspace`

In [96]:
# Hàm zeros: Dùng để tạo mảng toàn số 0
np.zeros([2,4],dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [97]:
# Hàm ones: Dùng để tạo mảng toàn số 1
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [98]:
# Hàm full
np.full((3,5),6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [99]:
# Hàm arange
# Bắt đầu từ 0, kết thúc 20, step: 2
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [100]:
# Hàm linspace
np.linspace(0,1,5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

##### random

In [101]:
# seed: cái này sẽ cho ra các lần random sẽ giống nhau
np.random.seed(0) 

np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [102]:
# rand: khai báo không cần dùng shape
np.random.rand(3,4)

array([[0.0202184 , 0.83261985, 0.77815675, 0.87001215],
       [0.97861834, 0.79915856, 0.46147936, 0.78052918],
       [0.11827443, 0.63992102, 0.14335329, 0.94466892]])

In [103]:
# normal: random với độ lệch chuẩn
# Giải thích:
# Tham số thứ nhất (0): giá trị trung bình (mean) của phân phối chuẩn.
# Tham số thứ hai (1): độ lệch chuẩn (standard deviation) của phân phối chuẩn.
# Tham số thứ ba ((3,3)): kích thước của mảng kết quả (3 hàng, 3 cột).
np.random.normal(0,1,(3,3))


array([[-2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567],
       [ 0.04575852, -0.18718385,  1.53277921]])

In [104]:
# randint: random với các số nguyên
np.random.randint(0,10,(3,5))

array([[4, 9, 8, 1, 1],
       [7, 9, 9, 3, 6],
       [7, 2, 0, 3, 5]], dtype=int32)

### Array Indexing & Slicing

##### One-dimensional subarray

In [105]:
x1 = np.random.randint(20,size = 6)
print(x1)

[12 10 11  4  6  4]


In [106]:
print(x1[4],x1[0],x1[-1])

6 12 4


##### Multi-dimensional array

In [107]:
x2 = np.random.randint(10,size=(3,4))
print(x2)

[[4 3 4 4]
 [8 4 3 7]
 [5 5 0 1]]


In [108]:
x2[1,1]

np.int32(4)

In [109]:
x2[0,0] = 0
x2

array([[0, 3, 4, 4],
       [8, 4, 3, 7],
       [5, 5, 0, 1]], dtype=int32)

##### Slicing

##### `x[start:stop:step]` 

In [110]:
x1

array([12, 10, 11,  4,  6,  4], dtype=int32)

In [111]:
x1[0:3]

array([12, 10, 11], dtype=int32)

In [112]:
x1[3:6]

array([4, 6, 4], dtype=int32)

In [113]:
# every other element, every 2 step
x1[::2]

array([12, 11,  6], dtype=int32)

In [114]:
x2

array([[0, 3, 4, 4],
       [8, 4, 3, 7],
       [5, 5, 0, 1]], dtype=int32)

In [115]:
# two rows, three columns
# x2[0:2,0:3]
x2[:2,:3]

array([[0, 3, 4],
       [8, 4, 3]], dtype=int32)

In [116]:
x2[:,:2]

array([[0, 3],
       [8, 4],
       [5, 5]], dtype=int32)

### Reshaping of Array & Transpose

In [117]:
grid = np.arange(1,10)
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
grid.shape

(9,)

In [119]:
grid.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [120]:
x = np.array([1,2,3])
x.shape

(3,)

In [121]:
x.reshape((1,3)).shape


(1, 3)

In [122]:
x = np.array([[1.,2.,5.],[3.,4.,6.]])
x

array([[1., 2., 5.],
       [3., 4., 6.]])

In [123]:
# Transpose: mảng.T 
# sẽ chuyển dòng thành cột, cột thành dòng
x.T

array([[1., 3.],
       [2., 4.],
       [5., 6.]])

### Array Concatenation and Splitting

In [124]:
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate((x,y))

array([1, 2, 3, 3, 2, 1])

In [125]:
# axis = 0 by default
# axis = 1: Sẽ nối theo chiều dọc
grid = np.array([[1,2,3],[4,5,6]])
grid
# np.concatenate((grid,grid))
np.concatenate((grid,grid),axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [126]:
#vstack
x = np.array([1,2,3])
grid = np.array([[9,8,7],[6,5,4]])


In [127]:
np.vstack((x,grid))

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [128]:
#horizontally stack the arrays: hstack
y = np.array([[99],[99]])
np.hstack((y,grid))

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

##### Splitting of arrays

In [129]:
x = np.array([1,2,3,99,69,3,2,1])

In [130]:
x1, x2, x3 = np.split(x,[3,5])

In [131]:
x1

array([1, 2, 3])

In [132]:
x2

array([99, 69])

In [133]:
x3

array([3, 2, 1])

### Broadcasting and Vectorized operations

In [134]:
a = np.arange(3)
a

array([0, 1, 2])

In [135]:
a + 5 #Broadcasting

array([5, 6, 7])

In [136]:
b = np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [137]:
a.shape,b.shape


((3,), (3, 3))

In [138]:
a+b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [139]:
c = np.arange(3).reshape((3,1))
c

array([[0],
       [1],
       [2]])

In [140]:
a+c

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### Manipulating & Comparing Arrays

In [141]:
list_number = [1,2,3]
ll = np.array(list_number)
ll

array([1, 2, 3])

In [142]:
# Python sum()
sum(ll) 

np.int64(6)

In [143]:
# Numpy sum
np.sum(ll)

np.int64(6)

In [144]:
# Create a massive Numpy array
massive_array = np.random.random(10000)
massive_array[:5]

array([0.77834548, 0.94957105, 0.66252687, 0.01357164, 0.6228461 ])

In [145]:
%timeit sum(massive_array) # Python built-in function sum()
%timeit np.sum(massive_array) # Numpy's np.sum()

443 μs ± 11.1 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
3.43 μs ± 33.1 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [146]:
np.mean(massive_array)

np.float64(0.5014384851964334)

In [147]:
np.max(massive_array)

np.float64(0.9999709462497284)

In [148]:
np.min(massive_array)

np.float64(2.0027530115096503e-05)

In [149]:
# Standard Deviation & Variance
dog_height = [600,470,170,340,300]
dog_height = np.array(dog_height)

np.std(dog_height)

np.float64(147.32277488562318)

In [150]:
np.var(dog_height)

np.float64(21704.0)

In [151]:
np.sqrt(np.var(dog_height))

np.float64(147.32277488562318)

### Sorting Arrays
np.sort uses an quicksort algorithm

In [152]:
x = np.array([5,2,3,4,1])
np.sort(x)

array([1, 2, 3, 4, 5])

In [153]:
# A related function is argsort, which instead returns the indices of the sorted elements:
np.argsort(x)

array([4, 1, 2, 3, 0])

##### Sorting along rows or columns

In [154]:
np.random.seed(42)
MatA = np.random.randint(0,10, size=(4,6))
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]], dtype=int32)

In [155]:
# axis = 0: sorting along columns
np.sort(MatA,axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]], dtype=int32)

In [156]:
np.sort(MatA,axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]], dtype=int32)

### Linear Algebra

In [157]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [158]:
B = np.array([[6,5],
              [4,3],
              [2,1]])
B

array([[6, 5],
       [4, 3],
       [2, 1]])

In [159]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [160]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [161]:
# B(3x2) dot A (3x3)
B.T #(2x3)


array([[6, 4, 2],
       [5, 3, 1]])

In [162]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

### Dot product example

In [163]:
# Number of jars sold
np.random.seed(0)
sales_amounts = np.random.randint(20, size=(5,3))


In [164]:
# Create weekly_sales DataFrame
import pandas as pd
weekly_sales = pd.DataFrame(sales_amounts, index=["Mon","Tues","Web","Thurs","Fri"],
                            columns=["Almond Butter", "Peanut Butter","Cashew Butter"])
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Web                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [165]:
# Create a price array
prices = np.array([10,8,12])
butter_prices = pd.DataFrame(prices.reshape(1,3),index=["Price"], columns=["Almond Butter", "Peanut Butter","Cashew Butter"])
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [166]:
weekly_sales.shape, butter_prices.T.shape

((5, 3), (3, 1))

In [167]:
total_prices = weekly_sales.dot(butter_prices.T)
total_prices

Price
Mon      240
Tues     138
Web      458
Thurs    232
Fri      142

In [168]:
weekly_sales["Total Price"] = total_prices
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total Price
Mon               12             15              0          240
Tues               3              3              7          138
Web                9             19             18          458
Thurs              4              6             12          232
Fri                1              6              7          142